// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg.proto

package com.study.service;

public final class ProtoRequest {
  private ProtoRequest() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface msgInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 num1 = 1;
    /**
     * <code>required int32 num1 = 1;</code>
     */
    boolean hasNum1();
    /**
     * <code>required int32 num1 = 1;</code>
     */
    int getNum1();

    // required int32 num2 = 2;
    /**
     * <code>required int32 num2 = 2;</code>
     */
    boolean hasNum2();
    /**
     * <code>required int32 num2 = 2;</code>
     */
    int getNum2();

    // required string methodName = 3;
    /**
     * <code>required string methodName = 3;</code>
     */
    boolean hasMethodName();
    /**
     * <code>required string methodName = 3;</code>
     */
    java.lang.String getMethodName();
    /**
     * <code>required string methodName = 3;</code>
     */
    com.google.protobuf.ByteString
        getMethodNameBytes();
  }
  /**
   * Protobuf type {@code com.study.service.msgInfo}
   */
  public static final class msgInfo extends
      com.google.protobuf.GeneratedMessage
      implements msgInfoOrBuilder {
    // Use msgInfo.newBuilder() to construct.
    private msgInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private msgInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final msgInfo defaultInstance;
    public static msgInfo getDefaultInstance() {
      return defaultInstance;
    }

    public msgInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private msgInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              num1_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              num2_ = input.readInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              methodName_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.study.service.ProtoRequest.internal_static_com_study_service_msgInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.study.service.ProtoRequest.internal_static_com_study_service_msgInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.study.service.ProtoRequest.msgInfo.class, com.study.service.ProtoRequest.msgInfo.Builder.class);
    }

    public static com.google.protobuf.Parser<msgInfo> PARSER =
        new com.google.protobuf.AbstractParser<msgInfo>() {
      public msgInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new msgInfo(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<msgInfo> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 num1 = 1;
    public static final int NUM1_FIELD_NUMBER = 1;
    private int num1_;
    /**
     * <code>required int32 num1 = 1;</code>
     */
    public boolean hasNum1() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 num1 = 1;</code>
     */
    public int getNum1() {
      return num1_;
    }

    // required int32 num2 = 2;
    public static final int NUM2_FIELD_NUMBER = 2;
    private int num2_;
    /**
     * <code>required int32 num2 = 2;</code>
     */
    public boolean hasNum2() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 num2 = 2;</code>
     */
    public int getNum2() {
      return num2_;
    }

    // required string methodName = 3;
    public static final int METHODNAME_FIELD_NUMBER = 3;
    private java.lang.Object methodName_;
    /**
     * <code>required string methodName = 3;</code>
     */
    public boolean hasMethodName() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string methodName = 3;</code>
     */
    public java.lang.String getMethodName() {
      java.lang.Object ref = methodName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          methodName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string methodName = 3;</code>
     */
    public com.google.protobuf.ByteString
        getMethodNameBytes() {
      java.lang.Object ref = methodName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        methodName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      num1_ = 0;
      num2_ = 0;
      methodName_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasNum1()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasNum2()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMethodName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, num1_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, num2_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getMethodNameBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, num1_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, num2_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getMethodNameBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.study.service.ProtoRequest.msgInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.study.service.ProtoRequest.msgInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.study.service.ProtoRequest.msgInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.study.service.ProtoRequest.msgInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.study.service.ProtoRequest.msgInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.study.service.ProtoRequest.msgInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.study.service.ProtoRequest.msgInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.study.service.ProtoRequest.msgInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.study.service.ProtoRequest.msgInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.study.service.ProtoRequest.msgInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.study.service.ProtoRequest.msgInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.study.service.msgInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.study.service.ProtoRequest.msgInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.study.service.ProtoRequest.internal_static_com_study_service_msgInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.study.service.ProtoRequest.internal_static_com_study_service_msgInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.study.service.ProtoRequest.msgInfo.class, com.study.service.ProtoRequest.msgInfo.Builder.class);
      }

      // Construct using com.study.service.ProtoRequest.msgInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        num1_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        num2_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        methodName_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.study.service.ProtoRequest.internal_static_com_study_service_msgInfo_descriptor;
      }

      public com.study.service.ProtoRequest.msgInfo getDefaultInstanceForType() {
        return com.study.service.ProtoRequest.msgInfo.getDefaultInstance();
      }

      public com.study.service.ProtoRequest.msgInfo build() {
        com.study.service.ProtoRequest.msgInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.study.service.ProtoRequest.msgInfo buildPartial() {
        com.study.service.ProtoRequest.msgInfo result = new com.study.service.ProtoRequest.msgInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.num1_ = num1_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.num2_ = num2_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.methodName_ = methodName_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.study.service.ProtoRequest.msgInfo) {
          return mergeFrom((com.study.service.ProtoRequest.msgInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.study.service.ProtoRequest.msgInfo other) {
        if (other == com.study.service.ProtoRequest.msgInfo.getDefaultInstance()) return this;
        if (other.hasNum1()) {
          setNum1(other.getNum1());
        }
        if (other.hasNum2()) {
          setNum2(other.getNum2());
        }
        if (other.hasMethodName()) {
          bitField0_ |= 0x00000004;
          methodName_ = other.methodName_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasNum1()) {
          
          return false;
        }
        if (!hasNum2()) {
          
          return false;
        }
        if (!hasMethodName()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.study.service.ProtoRequest.msgInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.study.service.ProtoRequest.msgInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 num1 = 1;
      private int num1_ ;
      /**
       * <code>required int32 num1 = 1;</code>
       */
      public boolean hasNum1() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 num1 = 1;</code>
       */
      public int getNum1() {
        return num1_;
      }
      /**
       * <code>required int32 num1 = 1;</code>
       */
      public Builder setNum1(int value) {
        bitField0_ |= 0x00000001;
        num1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 num1 = 1;</code>
       */
      public Builder clearNum1() {
        bitField0_ = (bitField0_ & ~0x00000001);
        num1_ = 0;
        onChanged();
        return this;
      }

      // required int32 num2 = 2;
      private int num2_ ;
      /**
       * <code>required int32 num2 = 2;</code>
       */
      public boolean hasNum2() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 num2 = 2;</code>
       */
      public int getNum2() {
        return num2_;
      }
      /**
       * <code>required int32 num2 = 2;</code>
       */
      public Builder setNum2(int value) {
        bitField0_ |= 0x00000002;
        num2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 num2 = 2;</code>
       */
      public Builder clearNum2() {
        bitField0_ = (bitField0_ & ~0x00000002);
        num2_ = 0;
        onChanged();
        return this;
      }

      // required string methodName = 3;
      private java.lang.Object methodName_ = "";
      /**
       * <code>required string methodName = 3;</code>
       */
      public boolean hasMethodName() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string methodName = 3;</code>
       */
      public java.lang.String getMethodName() {
        java.lang.Object ref = methodName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          methodName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string methodName = 3;</code>
       */
      public com.google.protobuf.ByteString
          getMethodNameBytes() {
        java.lang.Object ref = methodName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          methodName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string methodName = 3;</code>
       */
      public Builder setMethodName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        methodName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string methodName = 3;</code>
       */
      public Builder clearMethodName() {
        bitField0_ = (bitField0_ & ~0x00000004);
        methodName_ = getDefaultInstance().getMethodName();
        onChanged();
        return this;
      }
      /**
       * <code>required string methodName = 3;</code>
       */
      public Builder setMethodNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        methodName_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.study.service.msgInfo)
    }

    static {
      defaultInstance = new msgInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.study.service.msgInfo)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_study_service_msgInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_study_service_msgInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tmsg.proto\022\021com.study.service\"9\n\007msgInf" +
      "o\022\014\n\004num1\030\001 \002(\005\022\014\n\004num2\030\002 \002(\005\022\022\n\nmethodN" +
      "ame\030\003 \002(\tB!\n\021com.study.serviceB\014ProtoReq" +
      "uest"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_study_service_msgInfo_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_study_service_msgInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_study_service_msgInfo_descriptor,
              new java.lang.String[] { "Num1", "Num2", "MethodName", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
